CAPTCHA_DETECTED_DELAY = 1 * 60
BATCH_SIZE_DELAY = 2 * 60
DELAY_BETWEEN_STEPS = 2 * 60
DELAY_BETWEEN_SEARCHES = 1 * 60
DELAY_BETWEEN_PAGES = 7
DELAY_BETWEEN_LINKS = 15
MAX_PAGES_TO_SCRAPE = 1
LIMITING_RESULTS = 50

# Do not change the following values
POST_CODE = 'TQ1 3RW'
DISCORD_MESSAGE_DELAY = 5
MAX_SHOW_MORE_CLICKS = 4
SCRAPING_URL_BATCH_SIZE = 10
CRON_JOB_INTERVAL = 60 * 60 * 12  # 12 hours
DAYS_TO_EXPIRE_OLD_PRODUCTS = 7
